# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    id: "xrootd-monitoring-shoveler"
    binary: xrootd-monitoring-shoveler
    main: .
    ignore:
      - goos: windows
        goarch: arm64
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    id: "createtoken"
    binary: createtoken
    main: ./cmd/createtoken
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - xrootd-monitoring-shoveler
      - createtoken
    wrap_in_directory: true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

nfpms:
  - package_name: xrootd-monitoring-shoveler
    builds:
      - xrootd-monitoring-shoveler
      - createtoken
    file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    id: xrootd-monitoring-shoveler
    vendor: Open Science Grid
    homepage: https://github.com/opensciencegrid/xrootd-monitoring-shoveler
    maintainer: Derek Weitzel <dweitzel@unl.edu>
    description: XRootD Monitoring Shoveler collects XRootD monitoring UDP packets and sends them to a message bus
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    release: 1
    section: default
    priority: extra
    overrides:
      rpm:
        replacements:
          amd64: x86_64
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Release }}.{{ .Arch }}"
      deb:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Release }}_{{ .Arch }}"

dockers:
  - image_templates:
      - "hub.opensciencegrid.org/opensciencegrid/xrootd-monitoring-collector:{{ .Tag }}"
      - "hub.opensciencegrid.org/opensciencegrid/xrootd-monitoring-collector:latest"
    # GOOS of the built binaries/packages that should be used.
    goos: linux

    # GOARCH of the built binaries/packages that should be used.
    goarch: amd64

    # IDs to filter the binaries/packages.
    ids:
      - xrootd-monitoring-shoveler
      - createtoken
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "opensciencegrid/xrootd-monitoring-collector:{{ .Tag }}"
      - "opensciencegrid/xrootd-monitoring-collector:latest"
      # GOOS of the built binaries/packages that should be used.
      goos: linux

      # GOARCH of the built binaries/packages that should be used.
      goarch: amd64

      # IDs to filter the binaries/packages.
      ids:
        - xrootd-monitoring-shoveler
        - createtoken
      build_flag_templates:
        - "--pull"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
