package collector

import (
	"context"
	"strings"

	"github.com/sirupsen/logrus"
)

// The network scope of a transfer, published as "traffic_scope" on the WLCG
// record. It is the canonical topology answer: "site_internal_traffic" is
// derived from it (see siteInternalFromScope), so the two can never disagree.
//
// UNKNOWN is a real answer, not a missing one: it says the collector could not
// settle both ends, which is different from having settled them and found them
// apart. Uppercase because these are network terms, not resolution outcomes;
// the per-endpoint statuses in sitemap.go keep their own lowercase vocabulary.
const (
	TrafficScopeLAN     = "LAN"     // both ends resolved to the same RCSite
	TrafficScopeWAN     = "WAN"     // both ends resolved, to different RCSites
	TrafficScopeUnknown = "UNKNOWN" // at least one end was not resolved
)

// The signals that mark an operation as generated by XRootD itself rather than
// by an end user. They are the "signal" label on shoveler_traffic_xrootd_internal
// and are a fixed set, so the label stays bounded.
const (
	TrafficSignalInternalUser = "internal_user"      // the account is a system account (wlcg.traffic_internal_users)
	TrafficSignalJobAgent     = "job_agent"          // the account is a numeric job-agent id in the configured range
	TrafficSignalReplication  = "replication"        // protocol, appinfo or path names a replication operation
	TrafficSignalStorage      = "storage_to_storage" // both ends are known storage servers (off by default, see storageEndpointSet)
)

// Defaults for the XRootD-internal rules, from the MonALISA xrootd collector's
// isActualUser (lia/Monitor/modules/monXrootd.java): an operation is not a real
// user's when the account is "root", a single job-agent digit 1-8, or "daemon"
// running a "/replicate:" path.
var (
	// DefaultTrafficInternalUsers are the accounts XRootD uses for its own work.
	DefaultTrafficInternalUsers = []string{"root"}

	// DefaultTrafficReplicationPrefixes match a replication operation. MonALISA
	// looks for "/replicate:" in the path; the prefix is matched against each
	// "/"-separated segment, so it covers that form and a bare "replicate"
	// protocol too.
	DefaultTrafficReplicationPrefixes = []string{"replicate"}
)

// The XRootD job-agent/system accounts are reported as a bare number. MonALISA
// accepts a single digit 1-8; the range is configurable here (min > max turns
// the rule off).
const (
	DefaultTrafficJobAgentMin = 1
	DefaultTrafficJobAgentMax = 8
)

// TrafficConfig holds the deployment-specific parts of the classification, so
// the rules are not buried in the classifier. It applies only in WLCG mode; see
// shoveler.WLCGConfig for the keys behind each field.
type TrafficConfig struct {
	// Enabled turns the classification on. It defaults to true, but takes effect
	// only while wlcg.enabled is on: the three fields are emitted on the WLCG
	// record only.
	Enabled bool

	// InternalUsers are accounts whose operations are XRootD's own work, matched
	// exactly against the account the 'u' stream reported. Empty means
	// DefaultTrafficInternalUsers.
	InternalUsers []string

	// JobAgentMin/JobAgentMax bound the numeric job-agent accounts, matched when
	// the account is all digits. Both unset means 1-8; a max below the min turns
	// the rule off.
	JobAgentMin int
	JobAgentMax int

	// ReplicationPrefixes mark a replication operation, matched against the start
	// of each "/"-separated segment of the protocol, the appinfo and the path.
	// Empty means DefaultTrafficReplicationPrefixes.
	ReplicationPrefixes []string

	// CaseSensitive matches accounts and replication prefixes exactly as written.
	// Default false: XRootD account names and protocols arrive in whatever case
	// the client used, and "Root" is the same account as "root".
	CaseSensitive bool
}

// storageEndpointSet reports whether one end of a transfer is a storage server
// belonging to the monitored infrastructure, which would make a transfer
// between two of them XRootD's own work regardless of the account.
//
// Nothing implements it in production and the classifier's field is nil, so the
// signal is off: learning storage addresses from observed writes needs state
// that survives restarts, expires stale addresses, stays bounded, and is not
// confused by several collectors each seeing a different slice of the traffic.
// None of that exists here yet, so the check is defined as a seam rather than
// guessed at. The account and replication rules do not depend on it.
type storageEndpointSet interface {
	// IsStorageEndpoint reports whether host (a name or an address literal) is a
	// known storage server. It must be safe for concurrent use.
	IsStorageEndpoint(host string) bool
}

// withDefaults fills in the rules the operator said nothing about. A job-agent
// range is "said nothing about" only when neither end is set: an explicit min
// with a lower max is how the numeric rule is turned off.
func (c TrafficConfig) withDefaults() TrafficConfig {
	if len(c.InternalUsers) == 0 {
		c.InternalUsers = DefaultTrafficInternalUsers
	}
	if len(c.ReplicationPrefixes) == 0 {
		c.ReplicationPrefixes = DefaultTrafficReplicationPrefixes
	}
	if c.JobAgentMin <= 0 && c.JobAgentMax <= 0 {
		c.JobAgentMin, c.JobAgentMax = DefaultTrafficJobAgentMin, DefaultTrafficJobAgentMax
	}
	return c
}

// trafficClassifier answers the one question "was this XRootD's own work?" from
// a record. It holds the normalized rules so each record costs only lookups.
type trafficClassifier struct {
	internalUsers       map[string]struct{}
	jobAgentMin         int
	jobAgentMax         int
	replicationPrefixes []string
	caseSensitive       bool

	// storage is the deferred storage-to-storage check; nil disables it.
	storage storageEndpointSet
}

// newTrafficClassifier compiles a TrafficConfig into a classifier, applying the
// defaults for anything left unset. The defaults live here rather than in the
// config layer so there is one copy of each, as with NormalizeVOOrder and
// NormalizeSiteResolutionOrder.
func newTrafficClassifier(cfg TrafficConfig) *trafficClassifier {
	cfg = cfg.withDefaults()

	c := &trafficClassifier{
		jobAgentMin:   cfg.JobAgentMin,
		jobAgentMax:   cfg.JobAgentMax,
		caseSensitive: cfg.CaseSensitive,
	}

	c.internalUsers = make(map[string]struct{}, len(cfg.InternalUsers))
	for _, user := range cfg.InternalUsers {
		if u := c.fold(user); u != "" {
			c.internalUsers[u] = struct{}{}
		}
	}

	c.replicationPrefixes = make([]string, 0, len(cfg.ReplicationPrefixes))
	for _, prefix := range cfg.ReplicationPrefixes {
		if p := c.fold(prefix); p != "" {
			c.replicationPrefixes = append(c.replicationPrefixes, p)
		}
	}

	return c
}

// fold normalizes a value for comparison: trimmed, and lowercased unless the
// operator asked for exact matching.
func (t *trafficClassifier) fold(value string) string {
	v := strings.TrimSpace(value)
	if t.caseSensitive {
		return v
	}
	return strings.ToLower(v)
}

// ClassifyXRootDInternal reports whether the record looks like XRootD's own
// work, and which signal said so. The signals are OR-ed and checked in a fixed
// order, so the reported one is the first that matched:
//
//  1. the account is a configured system account ("root")
//  2. the account is a numeric job-agent id in the configured range (1-8)
//  3. the protocol, appinfo or path names a replication operation ("replicate")
//  4. both ends are known storage servers (off; see storageEndpointSet)
//
// Nothing else counts. A record whose account never reached the collector, or
// that carries none of these markers, is reported as not internal (false)
// rather than unknown: the schema has no unknown state for it, and calling an
// ordinary user's transfer infrastructure traffic is the worse mistake.
func (t *trafficClassifier) ClassifyXRootDInternal(record *CollectorRecord) (internal bool, signal string) {
	if record == nil {
		return false, ""
	}

	// A record names its account in two places and the system accounts show up in
	// both, so both are judged (see recordAccounts).
	for _, account := range recordAccounts(record) {
		user := t.fold(account)
		if user == "" {
			continue
		}
		if _, ok := t.internalUsers[user]; ok {
			return true, TrafficSignalInternalUser
		}
		if t.isJobAgentID(user) {
			return true, TrafficSignalJobAgent
		}
	}

	// MonALISA looks for "/replicate:" in the dict info, which is the path for a
	// transfer and the appinfo for an application record; the protocol is checked
	// too so a replication protocol is caught on its own.
	if t.isReplicationOperation(record.Protocol) ||
		t.isReplicationOperation(record.AppInfo) ||
		t.isReplicationOperation(record.Filename) {
		return true, TrafficSignalReplication
	}

	if t.isStorageToStorage(record) {
		return true, TrafficSignalStorage
	}

	return false, ""
}

// recordAccounts returns the account names a record can be judged on, in a fixed
// array so classifying a record allocates nothing. Either may be empty.
//
// [0] is the account the 'u' stream reported alongside the protocol and host,
// and it is taken only when user info was actually correlated: without it the
// record carries a hex of the numeric user id (see BuildUserHex), which for a
// low id is indistinguishable from a job-agent account — a missing input, not a
// signal.
//
// [1] is what user_dn names. Despite the name that field is the auth stream's
// "n=" value, which in production is usually a mapped account rather than a
// distinguished name, and it is where the system accounts actually show up:
// "root" and "daemon" appear there on records whose "user" is an ordinary
// account or a hex fallback. It needs no correlation guard of its own, since a
// record only has a DN when its user info was correlated.
func recordAccounts(record *CollectorRecord) [2]string {
	accounts := [2]string{}
	if record.userInfoKnown {
		accounts[0] = record.User
	}
	accounts[1] = accountFromUserDN(record.UserDN)
	return accounts
}

// accountFromUserDN reads the account out of a user_dn value: the CN when it is
// a real distinguished name, and the value itself when it is a bare account
// name, which is the common case.
//
// This is deliberately a superset of what ConvertToWLCG publishes as "user",
// which takes the CN and nothing else: a bare account is an identity worth
// classifying on even though the WLCG record does not republish it there. The
// record still carries it, as user_dn.
func accountFromUserDN(dn string) string {
	value := strings.TrimSpace(dn)
	if value == "" {
		return ""
	}
	if idx := strings.LastIndex(value, "CN="); idx >= 0 {
		return strings.TrimSpace(value[idx+len("CN="):])
	}
	// A DN with no CN names no account; anything without DN punctuation is the
	// account itself.
	if strings.ContainsAny(value, "=/") {
		return ""
	}
	return value
}

// isJobAgentID reports whether an account is one of the numeric job-agent ids.
// The account must be all digits: XRootD reports these agents as a bare number,
// so anything else is a name that merely starts with one.
func (t *trafficClassifier) isJobAgentID(user string) bool {
	if t.jobAgentMax < t.jobAgentMin {
		return false
	}

	id := 0
	for _, r := range user {
		if r < '0' || r > '9' {
			return false
		}
		id = id*10 + int(r-'0')
		if id > t.jobAgentMax {
			// Also stops a long digit string from overflowing.
			return false
		}
	}
	if user == "" {
		return false
	}

	return id >= t.jobAgentMin
}

// isReplicationOperation reports whether a value names a replication operation:
// any of its "/"-separated segments starts with a configured prefix. Splitting
// on "/" is what makes "/replicate:xyz" inside a path match while an ordinary
// path that merely contains the letters does not.
func (t *trafficClassifier) isReplicationOperation(value string) bool {
	if len(t.replicationPrefixes) == 0 {
		return false
	}
	v := t.fold(value)
	if v == "" {
		return false
	}

	for _, segment := range strings.Split(v, "/") {
		if segment == "" {
			continue
		}
		for _, prefix := range t.replicationPrefixes {
			if strings.HasPrefix(segment, prefix) {
				return true
			}
		}
	}
	return false
}

// isStorageToStorage reports whether both ends of the transfer are known
// storage servers. It is always false unless a storageEndpointSet is wired in,
// which nothing does yet.
func (t *trafficClassifier) isStorageToStorage(record *CollectorRecord) bool {
	if t.storage == nil {
		return false
	}
	server, client := record.ServerHostname, record.clientHost()
	if server == "" || client == "" {
		return false
	}
	return t.storage.IsStorageEndpoint(server) && t.storage.IsStorageEndpoint(client)
}

// classifyTrafficScope turns the two per-endpoint site resolutions into the
// record's scope. Both ends must have resolved for the scope to be anything but
// UNKNOWN: an ambiguous match names a site but is explicitly a guess (see
// SiteRegistry.resolveHost), and guessing here would produce a definite LAN or
// WAN from an undecided endpoint.
func classifyTrafficScope(srcSite, srcStatus, dstSite, dstStatus string) string {
	if !siteStatusResolved(srcStatus) || !siteStatusResolved(dstStatus) {
		return TrafficScopeUnknown
	}
	// Defence in depth: a resolved status always carries a site name.
	if srcSite == "" || dstSite == "" {
		return TrafficScopeUnknown
	}
	if srcSite == dstSite {
		return TrafficScopeLAN
	}
	return TrafficScopeWAN
}

// siteStatusResolved reports whether a per-endpoint status settled the endpoint.
// "ambiguous" is deliberately not one of them (see classifyTrafficScope).
func siteStatusResolved(status string) bool {
	switch status {
	case SiteStatusResolved, SiteStatusResolvedConfig, SiteStatusResolvedOverride,
		SiteStatusResolvedHostname, SiteStatusResolvedIP:
		return true
	default:
		return false
	}
}

// siteInternalFromScope derives site_internal_traffic from the scope, which is
// the only place the two are related: LAN is internal, WAN is not, and an
// unresolved topology has no answer at all (nil, so the field is left off the
// record rather than published as a false).
func siteInternalFromScope(scope string) *bool {
	internal := true
	external := false
	switch scope {
	case TrafficScopeLAN:
		return &internal
	case TrafficScopeWAN:
		return &external
	default:
		return nil
	}
}

// trafficRecordEnricher stamps the scope and the XRootD-internal verdict on a
// record. It must run AFTER siteRecordEnricher, whose src/dst resolution the
// scope is read from.
//
// The two classifications are independent: a record can be LAN and internal,
// LAN and a user's, WAN and internal, or WAN and a user's. Neither filters the
// other, and an UNKNOWN scope does not stop the origin from being classified.
type trafficRecordEnricher struct {
	classifier *trafficClassifier

	// wlcgOnly gates the work, like the site enricher: the fields are emitted on
	// WLCG records only, so classifying anything else would be thrown away. nil
	// classifies every record, which is what the unit tests want.
	wlcgOnly func(*CollectorRecord) bool
}

func (t *trafficRecordEnricher) Name() string { return "traffic" }

func (t *trafficRecordEnricher) Enrich(_ context.Context, record *CollectorRecord) {
	if record == nil || t.classifier == nil {
		return
	}
	if t.wlcgOnly != nil && !t.wlcgOnly(record) {
		return
	}

	scope := classifyTrafficScope(record.srcSite, record.srcSiteStatus, record.dstSite, record.dstSiteStatus)
	internal, signal := t.classifier.ClassifyXRootDInternal(record)

	record.trafficScope = scope
	record.xrootdInternal = internal

	trafficScopeTotal.WithLabelValues(scope).Inc()
	if internal {
		trafficXRootDInternal.WithLabelValues(signal).Inc()
	}
}

// logTrafficRules states the rules in force once at startup, the way the site
// resolver logs its order. Per-record reasons are not logged: there are
// millions of records and the account is user information.
func logTrafficRules(logger *logrus.Logger, cfg TrafficConfig) {
	if logger == nil {
		return
	}
	// The rules as they are actually applied, not as they were configured: an
	// unset one is the default, and that is what an operator needs to see.
	cfg = cfg.withDefaults()
	logger.Infof("traffic: xrootd-internal rules: users %v, job-agent ids %d-%d, replication prefixes %v (case-sensitive %t)",
		cfg.InternalUsers, cfg.JobAgentMin, cfg.JobAgentMax, cfg.ReplicationPrefixes, cfg.CaseSensitive)
}
